# Generated by Django 4.2.5 on 2023-09-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('inicio', models.DateField(auto_now_add=True)),
                ('fin', models.DateField(auto_now=True)),
                ('duracion', models.IntegerField()),
            ],
            options={
                'verbose_name': 'carrera',
                'verbose_name_plural': 'carreras',
                'db_table': 'carreras',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.IntegerField()),
                ('carreras_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.carrera')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'db_table': 'cursos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('inscripcion', models.DateTimeField(auto_now_add=True)),
                ('cursos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.curso')),
            ],
            options={
                'verbose_name': 'alumno',
                'verbose_name_plural': 'alumnos',
                'db_table': 'alumnos',
                'ordering': ('apellido', 'nombre'),
            },
        ),
    ]
