# Generated by Django 4.2.5 on 2023-10-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='fin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
